### ISSUE TITLE
您好，数据方面想请教

### ISSUE THREAD

**Issue by XueCes** [slzhou-xy/GRLSTM#1]
作者您好，我想使用自己的数据集，但是好像TS-Join的方法没开源，请你方便给一份数据预处理的代码嘛，十分感谢

**Comment by slzhou-xy** [comment]
请邮箱联系我



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月9日(周一) 晚上7:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [slzhou-xy/GRLSTM] 您好，数据方面想请教 (Issue #1)




 
作者您好，我想使用自己的数据集，但是好像TS-Join的方法没开源，请你方便给一份数据预处理的代码嘛，十分感谢

**Comment by XueCes** [comment]
作者您好！已发您论文中的谷歌邮箱，如果不是的话能否留一个邮箱，感激不尽
